AnimalAI:
    trainer: ppo
    epsilon: 0.2
    lambd: 0.90
    learning_rate: 4.0e-4
>>>>>>> dd6d70a2d7bb1023ffffa70647710dcdf78f66f5
    learning_rate_schedule: linear
    memory_size: 128
    normalize: false
    sequence_length: 64
    summary_freq: 10000
    use_recurrent: false
    # vis_encode_type: simple    time_horizon: 128
    batch_size: 128
    buffer_size: 2048
    hidden_units: 128
=======
    batch_size: 64
    buffer_size: 2024
    hidden_units: 256
>>>>>>> dd6d70a2d7bb1023ffffa70647710dcdf78f66f5
    num_layers: 1
    beta: 1.0e-2
    max_steps: 1.0e7
    num_epoch: 3
    reward_signals:
        extrinsic:
            strength: 1.0
<<<<<<< HEAD
            gamma: 0.90
#        curiosity:
#            strength: 0.01
#            gamma: 0.99
#            encoding_size: 128
=======
            gamma: 0.99
        # curiosity:
        #     strength: 0.01
        #     gamma: 0.99
        #     encoding_size: 128
>>>>>>> dd6d70a2d7bb1023ffffa70647710dcdf78f66f5
