AnimalAI:
    trainer: sac
    learning_rate: 3.0e-4
    learning_rate_schedule: linear
    memory_size: 128
    normalize: false
    sequence_length: 64
    summary_freq: 10000
    use_recurrent: false
    vis_encode_type: simple
    time_horizon: 128
    batch_size: 64
    buffer_size: 100000
    buffer_init_steps: 2000
    hidden_units: 256
    num_layers: 1
    beta: 1.0e-2
    max_steps: 1.0e7
    num_epoch: 3
    num_update: 1
    init_entcoef: 0.25
    train_interval: 5
    steps_per_update: 8
    tau: 0.01
    reward_signals:
        extrinsic:
            strength: 1.0
            gamma: 0.99
        curiosity:
            strength: 0.01
            gamma: 0.99
            encoding_size: 256