# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: animalai/communicator_objects/unity_rl_reset_output.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='animalai/communicator_objects/unity_rl_reset_output.proto',
  package='communicator_objects',
  syntax='proto3',
  serialized_options=_b('\252\002\034MLAgents.CommunicatorObjects'),
  serialized_pb=_b('\n9animalai/communicator_objects/unity_rl_reset_output.proto\x12\x14\x63ommunicator_objects\"1\n\x12UnityRLResetOutput\x12\x1b\n\x13\x61renas_instanciated\x18\x01 \x03(\x08\x42\x1f\xaa\x02\x1cMLAgents.CommunicatorObjectsb\x06proto3')
)




_UNITYRLRESETOUTPUT = _descriptor.Descriptor(
  name='UnityRLResetOutput',
  full_name='communicator_objects.UnityRLResetOutput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='arenas_instanciated', full_name='communicator_objects.UnityRLResetOutput.arenas_instanciated', index=0,
      number=1, type=8, cpp_type=7, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=132,
)

DESCRIPTOR.message_types_by_name['UnityRLResetOutput'] = _UNITYRLRESETOUTPUT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UnityRLResetOutput = _reflection.GeneratedProtocolMessageType('UnityRLResetOutput', (_message.Message,), {
  'DESCRIPTOR' : _UNITYRLRESETOUTPUT,
  '__module__' : 'animalai.communicator_objects.unity_rl_reset_output_pb2'
  # @@protoc_insertion_point(class_scope:communicator_objects.UnityRLResetOutput)
  })
_sym_db.RegisterMessage(UnityRLResetOutput)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
