# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: animalai/communicator_objects/arena_configuration_proto.proto

import sys

_b = sys.version_info[0] < 3 and (lambda x: x) or (lambda x: x.encode("latin1"))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from animalai.communicator_objects import (
    items_to_spawn_proto_pb2 as animalai_dot_communicator__objects_dot_items__to__spawn__proto__pb2,
)


DESCRIPTOR = _descriptor.FileDescriptor(
    name="animalai/communicator_objects/arena_configuration_proto.proto",
    package="communicator_objects",
    syntax="proto3",
    serialized_pb=_b(
        '\n=animalai/communicator_objects/arena_configuration_proto.proto\x12\x14\x63ommunicator_objects\x1a\x38\x61nimalai/communicator_objects/items_to_spawn_proto.proto"\x81\x01\n\x17\x41renaConfigurationProto\x12\t\n\x01t\x18\x01 \x01(\x05\x12\x11\n\tpass_mark\x18\x02 \x01(\x02\x12\x35\n\x05items\x18\x03 \x03(\x0b\x32&.communicator_objects.ItemToSpawnProto\x12\x11\n\tblackouts\x18\x04 \x03(\x05\x42\x14\xaa\x02\x11\x41\x41IOCommunicatorsb\x06proto3'
    ),
    dependencies=[
        animalai_dot_communicator__objects_dot_items__to__spawn__proto__pb2.DESCRIPTOR,
    ],
)


_ARENACONFIGURATIONPROTO = _descriptor.Descriptor(
    name="ArenaConfigurationProto",
    full_name="communicator_objects.ArenaConfigurationProto",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="t",
            full_name="communicator_objects.ArenaConfigurationProto.t",
            index=0,
            number=1,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="pass_mark",
            full_name="communicator_objects.ArenaConfigurationProto.pass_mark",
            index=1,
            number=2,
            type=2,
            cpp_type=6,
            label=1,
            has_default_value=False,
            default_value=float(0),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="items",
            full_name="communicator_objects.ArenaConfigurationProto.items",
            index=2,
            number=3,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="blackouts",
            full_name="communicator_objects.ArenaConfigurationProto.blackouts",
            index=3,
            number=4,
            type=5,
            cpp_type=1,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=146,
    serialized_end=275,
)

_ARENACONFIGURATIONPROTO.fields_by_name[
    "items"
].message_type = (
    animalai_dot_communicator__objects_dot_items__to__spawn__proto__pb2._ITEMTOSPAWNPROTO
)
DESCRIPTOR.message_types_by_name["ArenaConfigurationProto"] = _ARENACONFIGURATIONPROTO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ArenaConfigurationProto = _reflection.GeneratedProtocolMessageType(
    "ArenaConfigurationProto",
    (_message.Message,),
    dict(
        DESCRIPTOR=_ARENACONFIGURATIONPROTO,
        __module__="animalai.communicator_objects.arena_configuration_proto_pb2"
        # @@protoc_insertion_point(class_scope:communicator_objects.ArenaConfigurationProto)
    ),
)
_sym_db.RegisterMessage(ArenaConfigurationProto)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(
    descriptor_pb2.FileOptions(), _b("\252\002\021AAIOCommunicators")
)
# @@protoc_insertion_point(module_scope)
