# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from animalai.communicator_objects.vector_proto_pb2 import (
    VectorProto as animalai___communicator_objects___vector_proto_pb2___VectorProto,
)

from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
)

from google.protobuf.internal.containers import (
    RepeatedCompositeFieldContainer as google___protobuf___internal___containers___RepeatedCompositeFieldContainer,
    RepeatedScalarFieldContainer as google___protobuf___internal___containers___RepeatedScalarFieldContainer,
)

from google.protobuf.message import Message as google___protobuf___message___Message

from typing import (
    Iterable as typing___Iterable,
    Optional as typing___Optional,
    Text as typing___Text,
    Union as typing___Union,
)

from typing_extensions import Literal as typing_extensions___Literal

builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int
if sys.version_info < (3,):
    builtin___buffer = buffer
    builtin___unicode = unicode

class ItemToSpawnProto(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    name = ...  # type: typing___Text
    rotations = (
        ...
    )  # type: google___protobuf___internal___containers___RepeatedScalarFieldContainer[builtin___float]
    @property
    def positions(
        self,
    ) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[
        animalai___communicator_objects___vector_proto_pb2___VectorProto
    ]: ...
    @property
    def sizes(
        self,
    ) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[
        animalai___communicator_objects___vector_proto_pb2___VectorProto
    ]: ...
    @property
    def colors(
        self,
    ) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[
        animalai___communicator_objects___vector_proto_pb2___VectorProto
    ]: ...
    def __init__(
        self,
        *,
        name: typing___Optional[typing___Text] = None,
        positions: typing___Optional[
            typing___Iterable[
                animalai___communicator_objects___vector_proto_pb2___VectorProto
            ]
        ] = None,
        rotations: typing___Optional[typing___Iterable[builtin___float]] = None,
        sizes: typing___Optional[
            typing___Iterable[
                animalai___communicator_objects___vector_proto_pb2___VectorProto
            ]
        ] = None,
        colors: typing___Optional[
            typing___Iterable[
                animalai___communicator_objects___vector_proto_pb2___VectorProto
            ]
        ] = None,
    ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> ItemToSpawnProto: ...
    else:
        @classmethod
        def FromString(
            cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]
        ) -> ItemToSpawnProto: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions___Literal[
            "colors",
            b"colors",
            "name",
            b"name",
            "positions",
            b"positions",
            "rotations",
            b"rotations",
            "sizes",
            b"sizes",
        ],
    ) -> None: ...
